#!/bin/sh
# One-shot SoftHSM init: creates the PKCS#11 token (if not already there) and publishes the
# libsofthsm2.so module + its config onto bind-mounted volumes the `primodel` container also
# mounts, so the app's in-process PKCS#11 client (Net.Pkcs11Interop) can dlopen it. This container
# exits after init — the compose profile gates `primodel` on it via
# `condition: service_completed_successfully`.
#
# The AES KEK object itself is NOT generated here: the app generates it on first boot
# (PRIMODEL_KEK_PKCS11_CREATE_IF_MISSING=true) the first time it logs into the token — this
# sidecar's only job is to make the token exist and be reachable, so app boot and token init can't
# race each other for the get-started "spin everything up" flow to still land in ~60s.
set -eu

TOKEN_LABEL="${SOFTHSM_TOKEN_LABEL:-primodel-kek}"
USER_PIN="${SOFTHSM_PIN:-1234}"
SO_PIN="${SOFTHSM_SO_PIN:-5678}"
# These MUST be the same container-internal paths the primodel service mounts the same three host
# directories at (see docker-compose.yml) — directories.tokendir below is written using THIS
# container's view of the path, and the resulting softhsm2.conf is shared verbatim into primodel.
TOKEN_DIR="${SOFTHSM_TOKEN_DIR:-/opt/softhsm/tokens}"
CONF_DIR="${SOFTHSM_CONF_DIR:-/opt/softhsm/etc}"
LIB_DIR="${SOFTHSM_LIB_DIR:-/opt/softhsm/lib}"
SHARE_OWNER="${SOFTHSM_SHARE_OWNER:-1001:0}"

mkdir -p "$TOKEN_DIR" "$CONF_DIR" "$LIB_DIR"

CONF_FILE="$CONF_DIR/softhsm2.conf"
if [ ! -f "$CONF_FILE" ]; then
  cat > "$CONF_FILE" <<EOF
# Generated by the get-started SoftHSM init sidecar — shared read-only into the primodel container
# via SOFTHSM2_CONF. directories.tokendir MUST match the token volume's mount path as seen by
# whichever container is reading this file (both softhsm-init and primodel mount it at the same
# path, so one file works for both).
directories.tokendir = $TOKEN_DIR
objectstore.backend = file
log.level = INFO
EOF
fi
export SOFTHSM2_CONF="$CONF_FILE"

# Publish the PKCS#11 module onto the shared volume — the primodel image has no softhsm2 package of
# its own, so it can only load the library from a bind-mounted path. Vendor the transitive shared-lib
# deps too (best-effort: only those actually resolvable here) rather than assuming the primodel
# container's base image already has every one of them.
MODULE_SRC="$(find /usr/lib -name 'libsofthsm2.so' 2>/dev/null | head -n1)"
if [ -z "$MODULE_SRC" ]; then
  echo "softhsm-init: libsofthsm2.so not found — is the softhsm2 package installed in this image?" >&2
  exit 1
fi
cp -f "$MODULE_SRC" "$LIB_DIR/libsofthsm2.so"
for dep in $(ldd "$MODULE_SRC" 2>/dev/null | awk '{print $3}' | grep '^/'); do
  cp -n "$dep" "$LIB_DIR/" 2>/dev/null || true
done

# Idempotent token init: a fresh bind-mounted TOKEN_DIR is empty; a re-run against an already
# provisioned ./data/softhsm/tokens is not. Re-running --init-token would wipe the existing KEK the
# app generated on a previous boot, so skip entirely rather than trying to detect the label.
if [ -z "$(ls -A "$TOKEN_DIR" 2>/dev/null)" ]; then
  echo "softhsm-init: initializing token '$TOKEN_LABEL'..."
  softhsm2-util --init-token --free --label "$TOKEN_LABEL" --so-pin "$SO_PIN" --pin "$USER_PIN"
else
  echo "softhsm-init: token directory already populated — skipping init (existing KEK preserved)."
fi

# primodel runs as an arbitrary non-root UID in group 0 (Dockerfile: chgrp -R 0 + chmod g=u); make
# the shared volumes writable/readable by that group so it can log in and generate the KEK object.
chown -R "$SHARE_OWNER" "$TOKEN_DIR" "$CONF_DIR" "$LIB_DIR" 2>/dev/null || true
chmod -R g+rwX "$TOKEN_DIR" "$CONF_DIR"
chmod -R a+rX "$LIB_DIR"

echo "softhsm-init: ready (token='$TOKEN_LABEL', module='$LIB_DIR/libsofthsm2.so')."
